CREATE TABLE IF NOT EXISTS posts(
  id serial PRIMARY KEY,
	created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	uuid VARCHAR (32) UNIQUE NOT NULL,
	content VARCHAR NOT NULL
);

