"""empty message

Revision ID: e504aed97a38
Revises: 
Create Date: 2021-12-23 18:17:42.992148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e504aed97a38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_migrations')
    op.add_column('posts', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_constraint('posts_uuid_key', 'posts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('posts_uuid_key', 'posts', ['uuid'])
    op.drop_column('posts', 'deleted')
    op.create_table('schema_migrations',
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('dirty', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version', name='schema_migrations_pkey')
    )
    # ### end Alembic commands ###
